default_platform(:android)

platform :android do
  desc "Build and upload to Google Play (Internal Track)"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: "internal",
      release_status: "draft",
      metadata_path: "fastlane/metadata/android"
    )
  end
end
